version: "3.9"
services:
  postgres_db:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  movie_store_api_migrations:
    image: movie_store:latest
    container_name: movie_store_api_migrations
    command: python manage.py migrate
    depends_on:
      - postgres_db
  movie_store_api_loaddata:
    image: movie_store:latest
    container_name: movie_store_api_loaddata
    command: python manage.py loaddata common/tests/initial_data.json
    depends_on:
      - postgres_db
      - movie_store_api_migrations
  movie_store_api:
    image: movie_store:latest
    container_name: movie_store_api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
      - movie_store_api_migrations
