# Generated by Django 3.2 on 2021-04-10 15:05

from django.db import migrations
from movie_store.data.sample_data import genres, movies


def add_genres(apps, schema_editor):
    genre_model = apps.get_model('movie_store', 'Genre')
    for genre in genres:
        genre_model.objects.create(**genre)


def add_movies(apps, schema_editor):
    movie_model = apps.get_model('movie_store', 'Movie')
    genre_model = apps.get_model('movie_store', 'Genre')
    for movie in movies:
        movie_genres = genre_model.objects.filter(name__in=movie['genres'])
        new_movie = movie_model.objects.create(
            title=movie['title'],
            summary=movie['summary'],
            year=movie['year'],
            director=movie['director']
        )
        new_movie.genres.set(movie_genres)


class Migration(migrations.Migration):
    dependencies = [
        ('movie_store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_genres),
        migrations.RunPython(add_movies)
    ]
