# Generated by Django 3.2 on 2021-04-09 08:45

from django.db import migrations
import iam.managers


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', iam.managers.CustomUserManager()),
            ],
        ),
    ]
