"""
Django settings for movie_store_api project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '942w97oh5ymuo8c#_4cejzj)$lzl=o(9h7hk-3xo4)l&05u@b9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'iam.apps.IamConfig',
    'movie_store.apps.MovieStoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'ORDERING_PARAM': 'order_by',
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'iam.authentications.JWTCookieAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

ROOT_URLCONF = 'movie_store_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movie_store_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = "iam.CustomUser"


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Simple JWT settings
SIMPLEJWT_PRIVATE_KEY = '''-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAvZ75nNLe2bOCm7GU04YuZzBsl2AAf5MElkriZXUjo1oCdp2b
Vt3HU/E6c2Z0W8p3mIW7EC+M9qoGsmDzfRwUD3CD5+pIJuYDgz9dnziDtKqOaDxB
mYt+fF1em7it5Uit0vKEvNdH40quSPiYDe9Y52SG5IgEAKRFoP00BMS6ELqy2Aim
/+ws1LBsfZmqeWjmugNk+w6fdaRcwVXgLNweh6fTSxbjDZnZqiMQHfjli93vHQWS
diOG/h7xakRDfT78GTHUEEYjXuF0HDGn/bvmZ3EzT6PRHIL1UdOT8mr1rx+NQZTY
yD1bRM8KYWDpPjFY8GYUK+4GDli2r0DKmO71HwIDAQABAoIBAQCe7O8okVRWAi4l
b+DcqEmcEunwtXW1dvMRRBIcFuGXt4j5AX+AfsDhif0DW4uKo1c5blwqZLAwzLBw
MPHimfX2OsdTSPjQIVgwWJuPJz673XcdxeL1XgTVFyyEN3UIBrIpazn1TDnkNmN8
pV5Lz58j0Q193MH+B7CUDaPbm0aXXW/o7AdYS5rj7cIpf3ykM1kbG9Mkv1RrRim8
UJYEfOSCRHtGa5omOxJhUWxOfY6vPbltQ2j7bs447MlJ8iW4nBnxXLuYbpdppcQm
UenA3YdRuUkr09dJnxpixWUKE6knz3vV3duxYdnXXu+QIRp4TrFhJ0tKPtw9orJo
3YJRCAuBAoGBAPP6KjhbAUime8Sooxdj6i/O7DK1UzDKZ/IgZRuNxCC4flwC2+Qz
KLbJID2wdbNEDbxNeoegJIGDL6hGRgCrZgC02zGKslOnsuEKIv/attTL1zSj1r4P
P8e05bkdoE2VCViSwGOog/yjfYKTsXQEQ44xj2A4tHS95MHpOs0EXSOtAoGBAMb3
F7Nz1iVbbfjIDgkclEclAkAQs3ww90Q2oTDMpIO90dt0MeUxSsRXL/K3luVp1Ybz
DakUYBEm17YOdrGUxBck2RKTssJBJnTjRfzV9GbFSJZ49UDZji1hbEoqziV5y3gk
53c3JpAaFN9aeJlsceKu6i6vitGvT7b5s3awfDV7AoGADeaU/T0CJ7eEmcHZ+P0y
XKL3hjQal08Q+RSrbhR3tj2MxYVMLgZULYXsFle1fQ9FkRMBBjUzn0VwM7A9UNBz
MVscmggC/Q0y/etr7xPxEtLCYjdrhsyrn59I73EmrwTs0WUbHRJ+4qgWAJiVpbyQ
dMuSFbNlZLllDT9SoFe9TskCgYA4pnoVGlJK6LFzOGLmrUB60UrGuvqfzcFZpsRW
hK4C5LUv6vGZ9GL5bGm2jhdk0rF9bw7gqXCA8bJRn+Sjw1vhyxgTdgJb1PkCJwPy
bWjdKib00RPjlw4oVajjpTR07yzD1J4jD4znUsXGopfb90il5m+/QzQfZ+8mhgpX
LQDwqQKBgAkoQSXaoySCrIPOo+n7apuAE56Vh9NUSW7xNf1fDktZ46Y6K/5N6JgR
tUyzmV4U6+2zzQelkXMUQh/ZnYx09iJ39nbnJKPKx/N+RA+bW4nqlcmZerb6Vaai
HL6E7agiImieaJjIUHKARiY+xGLwOKjdQ47+QWRAS+MjicCWisns
-----END RSA PRIVATE KEY-----'''

SIMPLEJWT_PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvZ75nNLe2bOCm7GU04Yu
ZzBsl2AAf5MElkriZXUjo1oCdp2bVt3HU/E6c2Z0W8p3mIW7EC+M9qoGsmDzfRwU
D3CD5+pIJuYDgz9dnziDtKqOaDxBmYt+fF1em7it5Uit0vKEvNdH40quSPiYDe9Y
52SG5IgEAKRFoP00BMS6ELqy2Aim/+ws1LBsfZmqeWjmugNk+w6fdaRcwVXgLNwe
h6fTSxbjDZnZqiMQHfjli93vHQWSdiOG/h7xakRDfT78GTHUEEYjXuF0HDGn/bvm
Z3EzT6PRHIL1UdOT8mr1rx+NQZTYyD1bRM8KYWDpPjFY8GYUK+4GDli2r0DKmO71
HwIDAQAB
-----END PUBLIC KEY-----'''

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'RS512',
    'SIGNING_KEY': SIMPLEJWT_PRIVATE_KEY,
    'VERIFYING_KEY': SIMPLEJWT_PUBLIC_KEY,
    'USER_ID_FIELD': 'uuid',
    'USER_ID_CLAIM': 'user_uuid',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'AUTH_ACCESS_COOKIE': 'access',
    'AUTH_REFRESH_COOKIE': 'refresh',
}


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
